sonar.projectKey=AymanKamell_myapp-demo
sonar.organization=aymankamel

sonar.sources=backend/backend-application
sonar.tests=backend/backend-application/tests
sonar.exclusions=backend/backend-application/tests/**

sonar.python.coverage.reportPaths=backend/backend-application/coverage.xml

sonar.sourceEncoding=UTF-8
