name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  source-security:
    uses: ./.github/workflows/source-security.yml

  lint:
    uses: ./.github/workflows/lint.yml
