name: GitOps Deployment

on:
  workflow_call:
    inputs:
      image-ref:
        description: "Immutable image reference"
        required: true
        type: string

    secrets:
      GITOPS_TOKEN:
        required: true

jobs:
  gitops-deploy:
    name: Update GitOps Repository
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout GitOps repository
        uses: actions/checkout@v6
        with:
          repository: AymanKamell/myapp-gitops
          ref: main
          token: ${{ secrets.GITOPS_TOKEN }}
          path: myapp-gitops

      - name: Update backend image digest
        working-directory: myapp-gitops
        env:
          IMAGE_REF: ${{ inputs.image-ref }}
        run: |
          IMAGE_DIGEST="${IMAGE_REF##*@}"

          echo "Updating backend image digest to:"
          echo "$IMAGE_DIGEST"

          sed -i \
            "s|^\(\s*digest:\s*\).*|\1${IMAGE_DIGEST}|" \
            backend/kustomization.yaml

      - name: Verify change
        working-directory: myapp-gitops
        run: |
          git diff -- backend/kustomization.yaml

      - name: Commit and push GitOps change
        working-directory: myapp-gitops
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add backend/kustomization.yaml

          git commit \
            -m "Update backend image digest"

          git push origin main
