name: Backend CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build backend image
        run: |
          docker build -t myapp-backend:latest ./backend/backend-application/
