name: MyApp CI/CD

on:
  push:
    branches:
      - main

jobs:
  source-security:
    name: Source Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: .
          format: table
          severity: HIGH,CRITICAL
          exit-code: 1
          ignore-unfixed: true

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        working-directory: backend/backend-application
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        working-directory: backend/backend-application
        run: |
          pytest


  build:
    name: Build Backend OCI Artifact
    runs-on  : ubuntu-latest

    permissions:
      contents: read
      security-events: write

    needs:
      - source-security
      - test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Cosign
        uses: sigstore/cosign-installer@v4.0.0

      - name: Verify Cosign installation
        run: |
          cosign version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Build backend image
        run: |
          docker buildx build \
            --tag myapp-backend:ci \
            --load \
            --metadata-file build-metadata.json \
            ./backend/backend-application/

      - name: Get image digest
        run: |
          IMAGE_DIGEST=$(jq -r '.["containerimage.digest"]' build-metadata.json)

          echo "Image digest: $IMAGE_DIGEST"

          echo "IMAGE_REF=myapp-backend@${IMAGE_DIGEST}" >> "$GITHUB_ENV"
          echo "IMAGE_DIGEST=${IMAGE_DIGEST}" >> "$GITHUB_ENV"

      - name: Verify local image
        run: |
          docker image ls myapp-backend

          echo ""
          echo "Image reference:"
          echo "$IMAGE_REF"

          echo ""
          echo "Image inspect:"
          docker inspect myapp-backend:ci \
            --format '{{.Id}}'

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.6
        with:
          version: v0.69.3

      # --------------------------------------------------
      # Trivy Image Security Scan
      # --------------------------------------------------

      - name: Run Trivy image scan
        run: |
          trivy image \
            myapp-backend:ci \
            --severity HIGH,CRITICAL \
            --ignore-unfixed \
            --format sarif \
            --output trivy-image-results.sarif \
            --exit-code 1

      - name: Upload Trivy SARIF report
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-image-results.sarif

      # --------------------------------------------------
      # Trivy JSON Report
      # --------------------------------------------------

      - name: Generate Trivy JSON report
        if: always()
        run: |
          trivy image \
            myapp-backend:ci \
            --severity HIGH,CRITICAL \
            --ignore-unfixed \
            --format json \
            --output trivy-image-results.json \
            --exit-code 0

      # --------------------------------------------------
      # Trivy HTML Report
      # --------------------------------------------------

      - name: Download Trivy HTML template
        if: always()
        run: |
          curl -L \
            https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl \
            -o html.tpl

      - name: Generate Trivy HTML report
        if: always()
        run: |
          trivy image \
            myapp-backend:ci \
            --severity HIGH,CRITICAL \
            --ignore-unfixed \
            --format template \
            --template "@html.tpl" \
            --output trivy-image-results.html \
            --exit-code 0

      - name: Upload Trivy HTML report
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: trivy-image-html-report
          path: trivy-image-results.html
          if-no-files-found: error

      # --------------------------------------------------
      # GitHub Actions Security Summary
      # --------------------------------------------------

      - name: Add Trivy Image Scan summary
        if: always()
        run: |
          CRITICAL=$(jq '[.Results[]?.Vulnerabilities[]? | select(.Severity == "CRITICAL")] | length' trivy-image-results.json)
          HIGH=$(jq '[.Results[]?.Vulnerabilities[]? | select(.Severity == "HIGH")] | length' trivy-image-results.json)

          TOTAL=$((CRITICAL + HIGH))

          {
            echo "## Trivy Image Scan summary"
            echo ""

            if [ "$TOTAL" -eq 0 ]; then
              echo "# No HIGH or CRITICAL vulnerabilities detected ✅"
            else
              echo "# Vulnerabilities detected ❌"
            fi

            echo ""
            echo "| Severity | Count |"
            echo "|---|---:|"
            echo "| 🔴 CRITICAL | $CRITICAL |"
            echo "| 🟠 HIGH | $HIGH |"
            echo ""

            if [ "$TOTAL" -eq 0 ]; then
              echo "**Security gate:** ✅ PASSED"
            else
              echo "**Security gate:** ❌ FAILED"
              echo ""
              echo "The image contains HIGH or CRITICAL vulnerabilities."
            fi
          } >> "$GITHUB_STEP_SUMMARY"

      # --------------------------------------------------
      # Trivy JSON Artifact
      # --------------------------------------------------

      - name: Upload Trivy image report
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: trivy-image-report
          path: trivy-image-results.json
          if-no-files-found: error

      # --------------------------------------------------
      # SBOM
      # --------------------------------------------------

      - name: Generate SBOM
        run: |
          trivy image \
            myapp-backend:ci \
            --format spdx-json \
            --output myapp-backend.spdx.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v5
        with:
          name: myapp-backend-sbom
          path: myapp-backend.spdx.json
          if-no-files-found: error

      - name: Test Cosign SBOM attestation
        run: |
          echo "Image reference: $IMAGE_REF"
          echo "SBOM: myapp-backend.spdx.json"

          cosign attest \
          --yes \
          --type spdx \
          --predicate myapp-backend.spdx.json \
          "$IMAGE_REF"
      
  rhacs-scan:
    name: RHACS Image Scan
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read

    env:
      ROX_API_TOKEN: ${{ secrets.ROX_API_TOKEN }}
      ROX_ENDPOINT: ${{ vars.ROX_ENDPOINT }}

    steps:
      - name: Install roxctl
        run: |
          curl -L -o roxctl \
            https://mirror.openshift.com/pub/rhacs/assets/4.11.4/bin/Linux/roxctl
          chmod +x roxctl
          sudo mv roxctl /usr/local/bin/roxctl

      - name: RHACS image check
        run: |
          roxctl image check \
            -o table \
            --image="${{ vars.DOCKER_USERNAME }}/myapp-backend:latest"


  deploy:
    name: Deploy to OpenShift
    runs-on: ubuntu-latest
    needs: rhacs-scan
    permissions:
      contents: read

    env:
      OPENSHIFT_SERVER: ${{ vars.OPENSHIFT_SERVER }}
      OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}

    steps:
      - name: Install OpenShift CLI
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-linux.tar.gz
          tar -xzf openshift-client-linux.tar.gz
          sudo mv oc kubectl /usr/local/bin/

      - name: Configure OpenShift CA
        run: |
          echo "${{ secrets.OPENSHIFT_CA }}" > openshift-ca.crt

      - name: Log in to OpenShift
        run: |
          oc login "$OPENSHIFT_SERVER" \
            --token="$OPENSHIFT_TOKEN" \
            --certificate-authority=openshift-ca.crt

      - name: Update backend image
        run: |
          oc project myapp
          oc set image deployment/backend \
            backend=${{ vars.DOCKER_USERNAME }}/myapp-backend:latest

      - name: Wait for rollout
        run: |
          oc rollout status deployment/backend --timeout=5m
